Repository rlarjsdn3/ESTSoft-2th-Team2-2nd-Project, pull requests merged in 2025-06, with the labels that each got.

#11 feat: `PixabayResponse` 디코더블 구조체 작성, `pixabay(_:)`, `thumbnail(_:)` APIEndpoints 코드 구현
  Media.xcodeproj/project.pbxproj
  Media/Infrastructure/APIEndpoints.swift
  Media/Infrastructure/DataTransfer/Endpoint/Endpoint.swift
  Media/Infrastructure/DataTransfer/Endpoint/Requestable.swift
  Media/Infrastructure/DataTransfer/Network/NetworkConfiguration.swift
  Media/Model/API/Category.swift
  Media/Model/API/Order.swift
  Media/Model/Response/Mock/PixabayResponse.json
  Media/Model/Response/PixabayResponse+Mock.swift
  Media/Model/Response/PixabayResponse.swift
  Media/Presentation/Home/HomeViewController.swift
Labels: enhancement

#14 [Fix] home 스토리보드 table View > collection View로 수정
  Media/Presentation/Home/HomeViewController.storyboard
  Media/Presentation/Home/HomeViewController.swift
Labels: enhancement

#21 feat: 북마크 관련 Entity에 목 데이터 추가
  Media/Infrastructure/Storage/CoreData/CoreDataService+Dummy.swift
  Media/Model/CoreData/Media.xcdatamodeld/Media.xcdatamodel/contents
  Media/Model/CoreData/Playlist/PlaylistEntity+CoreDataProperties.swift
  Media/Presentation/Home/HomeViewController.swift
Labels: enhancement

#26 feat: 온보딩 파일 및 Tags CoreData 생성
  Media.xcodeproj/project.pbxproj
  Media/Model/CoreData/Media.xcdatamodeld/Media.xcdatamodel/contents.rej
  Media/Presentation/Onboarding/Cell/OnboardingTegsViewCell.swift
  Media/Presentation/Onboarding/OnBoardingOnBoardingViewController.storyboard
  Media/Presentation/Onboarding/OnBoardingTagsViewController.storyboard
  Media/Presentation/Onboarding/OnBoardingTagsViewController.swift
  Media/Presentation/Onboarding/OnboardingImageViewController.swift
Labels: enhancement

#28 [Feat] Home 화면 카테고리 임시로 지정 및 collection view추가 생성, Video 셀 틀만 생성
  Media/Presentation/Home/CategoryCell/CategoryCell.swift
  Media/Presentation/Home/CategoryCell/CategoryCell.xib
  Media/Presentation/Home/HomeViewController.storyboard
  Media/Presentation/Home/HomeViewController.swift
  Media/Presentation/Home/VideoCell/VideoCell.swift
  Media/Presentation/Home/VideoCell/VideoCell.xib
Labels: enhancement

#29 feat: Bookmark 컬렉션 뷰 셀에 ContextMenu 적용, 각 ContextMenu에 플레이리스트 CRUD 로직 구현, PlaylistVideos 화면에 기본 레이아웃 작성
  Media.xcodeproj/project.pbxproj
  Media/Core/Protocols/Alertable.swift
  Media/Infrastructure/Storage/CoreData/CoreDataService+Dummy.swift
  Media/Model/CoreData/Media.xcdatamodeld/Media.xcdatamodel/contents
  Media/Model/CoreData/PlaybackHistory/PlaybackHistoryEntity+CoreDataProperties.swift
  Media/Model/CoreData/Playlist/PlaylistEntity+CoreDataProperties.swift
  Media/Model/CoreData/PlaylistVideo/PlaylistVideoEntity+CoreDataProperties.swift
  Media/Model/CoreData/VideoQuality/VideoQualityEntity+CoreDataProperties.swift
  Media/Model/CoreData/VideoVariant/VideoVariantsEntity+CoreDataProperties.swift
  Media/Presentation/Bookmark/BookmarkViewController.storyboard
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/PlaylistVideosViewController.storyboard
  Media/Presentation/Bookmark/PlaylistVideosViewController.swift
  Media/Presentation/Bookmark/Section/BookmarkSection.swift
  Media/Presentation/Bookmark/Section/PlaylistSection.swift
  Media/Presentation/Bookmark/VideoLibraryViewController.storyboard
  Media/Presentation/Bookmark/VideoLibraryViewController.swift
Labels: enhancement

#32 [Feat] Home 화면 video api연결 및 디자인설정 및 폰트색상변경
  Media/Presentation/Home/CategoryCell/CategoryCell.swift
  Media/Presentation/Home/HomeViewController.storyboard
  Media/Presentation/Home/HomeViewController.swift
  Media/Presentation/Home/Video.swift
  Media/Presentation/Home/VideoCell/VideoCell.swift
  Media/Presentation/Home/VideoCell/VideoCell.xib
  Media/Presentation/Home/VideoCell/VideoCellUsing.swift
  Media/Presentation/Home/VideoCell/VideoCellViewModel.swift
Labels: enhancement

#34 Feat/#33 navigation bar UI 구현
  Media/Infrastructure/Storage/UserDefaults/UserDefaultsKeys.swift
  Media/Presentation/Bookmark/BookmarkViewController.storyboard
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/PlaylistVideosViewController.storyboard
  Media/Presentation/Bookmark/PlaylistVideosViewController.swift
  Media/Presentation/Bookmark/Section/BookmarkSection.swift
  Media/Presentation/Bookmark/Section/PlaylistSection.swift
  Media/Presentation/Bookmark/Section/VideoListSection.swift
  Media/Presentation/Bookmark/VideoListViewController.storyboard
  Media/Presentation/Bookmark/VideoListViewController.swift
Labels: enhancement

#42 [Feat] Home화면 카테고리 버튼 기능 활성화 및 비디오 연결, 비디오셀 디자인 수정
  Media/Infrastructure/DataTransfer/Endpoint/Requestable.swift
  Media/Presentation/Home/HomeViewController.swift
  Media/Presentation/Home/Video.swift
  Media/Presentation/Home/VideoCell/VideoCell.swift
  Media/Presentation/Home/VideoCell/VideoCell.xib
  Media/Presentation/Home/VideoCell/VideoCellViewModel.swift
Labels: enhancement

#44 feat: 시청 기록 및 플레이 리스트 상세 화면 별로 동작 방식 분기 처리, 북마크 화면에서 실제 셀로 대체 구현
  Media.xcodeproj/project.pbxproj
  Media/Core/Extensions/Date+Extension.swift
  Media/Core/Extensions/UICollectionView+Extension.swift
  Media/Core/Protocols/Alertable.swift
  Media/Core/Protocols/NibLodable.swift
  Media/Infrastructure/DataTransfer/Endpoint/Requestable.swift
  Media/Model/CoreData/Media.xcdatamodeld/Media.xcdatamodel/contents
  Media/Model/CoreData/PlaybackHistory/PlaybackHistoryEntity+CoreDataClass.swift
  Media/Model/CoreData/PlaybackHistory/PlaybackHistoryEntity+CoreDataProperties.swift
  Media/Model/CoreData/PlaybackHistory/PlaylistHistoryEntity+Mapping.swift
  Media/Model/CoreData/PlaylistVideo/PlaylistVideoEntity+CoreDataClass.swift
  Media/Model/CoreData/PlaylistVideo/PlaylistVideoEntity+CoreDataProperties.swift
  Media/Model/CoreData/PlaylistVideo/PlaylistVideoEntity+Mapping.swift
  Media/Model/CoreData/SearchRecord/SearchRecordEntity+CoreDataClass.swift
  Media/Model/CoreData/SearchRecord/SearchRecordEntity+CoreDataProperties.swift
  Media/Model/Response/PixabayResponse+Mapping.swift
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/Cells/HeaderReusableView.swift
  Media/Presentation/Bookmark/Cells/HeaderReusableView.xib
  Media/Presentation/Bookmark/Cells/SmallVideoCell.swift
  Media/Presentation/Bookmark/Cells/SmallVideoCell.xib
  Media/Presentation/Bookmark/Section/BookmarkSection.swift
  Media/Presentation/Bookmark/Section/VideoListSection.swift
  Media/Presentation/Bookmark/VideoListViewController.storyboard
  Media/Presentation/Bookmark/VideoListViewController.swift
  Media/Presentation/Home/VideoCell/VideoCell.swift
Labels: enhancement

#46 fix: 네비바 버튼 액션이 작동하지 않는 문제
  Media/Core/Common/NavigationBar/NavigationBar.swift
  Media/Core/Common/NavigationBar/NavigationBar.xib
Labels: bug

#51 feat: Bookmark 화면에서 재생목록 개수 제한, + 버튼 추가 및 재생목록 편집 등 기능 추가
  Media/Core/Protocols/Alertable.swift
  Media/Model/CoreData/PlaybackHistory/PlaybackHistoryEntity+CoreDataProperties.swift
  Media/Model/CoreData/PlaybackHistory/PlaylistHistoryEntity+Mapping.swift
  Media/Model/CoreData/Playlist/PlaylistEntity+Convenience.swift
  Media/Model/CoreData/Playlist/PlaylistEntity+Extension.swift
  Media/Model/CoreData/PlaylistVideo/PlaylistVideoEntity+CoreDataProperties.swift
  Media/Model/CoreData/PlaylistVideo/PlaylistVideoEntity+Mapping.swift
  Media/Model/Response/PixabayResponse.swift
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/Section/BookmarkSection.swift
  Media/Presentation/Bookmark/View/Cells/HeaderReusableView.swift
  Media/Presentation/Bookmark/View/Cells/HeaderReusableView.xib
  Media/Presentation/Bookmark/View/Cells/PlaylistDelegate.swift
  Media/Presentation/Bookmark/View/Cells/SmallVideoCell.swift
  Media/Presentation/Bookmark/View/Cells/SmallVideoCell.xib
Labels: enhancement

#68 [Feat] Home화면에서 Ellipsis버튼 메뉴 기능 활성화
  Media/Presentation/Home/HomeViewController.swift
  Media/Presentation/Home/VideoCell/VideoCell.swift
  Media/Presentation/Home/VideoCell/VideoCellViewModel.swift
Labels: enhancement

#71 [Fix] Home Ellipsis 메뉴버튼 재생목록생성시 토스트 수정 및 재생목록리스트에서 북마크 제외
  Media/Presentation/Home/HomeViewController.swift
Labels: enhancement

#87 feat: 북마크 및 재생 기록 상세 보기 화면에서 네비게이션 바, 셀 컨텐츠, 레이아웃 수치 등 UI 수정
  Media/Core/Extensions/UIViewController+Extension.swift
  Media/Core/Protocols/VideoPlayable.swift
  Media/Infrastructure/DataTransfer/Endpoint/Requestable.swift
  Media/Infrastructure/Storage/CoreData/CoreDataService+Dummy.swift
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/Section/BookmarkSection.swift
  Media/Presentation/Bookmark/Section/VideoListSection.swift
  Media/Presentation/Bookmark/VideoListViewController.swift
  Media/Presentation/Bookmark/View/Cells/MediumVideoCell.swift
  Media/Presentation/Bookmark/View/Cells/MediumVideoCell.xib
  Media/Presentation/Home/VideoCell/VideoCell.swift
  Media/Presentation/Home/VideoCell/VideoCell.xib
Labels: enhancement

#102 [Fix] 필터링 안되던 오류 수정완료
  Media/Presentation/Home/HomeViewController.swift
Labels: enhancement

#104 feat: UserDefaults에 저장되는 이름에 따라 북마크 네비게이션 타이틀이 변경되도록 구현, 재생 기록 셀에서 삭제 메뉴 기능 구현
  Media/Core/Common/ContentUnavailableView/ContentUnavailableView.xib
  Media/Core/Common/NavigationBar/NavigationBar.swift
  Media/Core/Common/PaddingLabel/PaddingLabel.swift
  Media/Core/Protocols/Alertable.swift
  Media/Model/CoreData/Playlist/PlaylistEntity+Convenience.swift
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/VideoListViewController.swift
  Media/Presentation/Bookmark/View/ColorCollecitonViewCell.swift
  Media/Presentation/Bookmark/View/ColorCollectiorReusableView.swift
  Media/Presentation/Bookmark/View/HeaderReusableView.xib
  Media/Presentation/Home/VideoCell/VideoCell.swift
  Media/Presentation/Home/VideoCell/VideoCell.xib
Labels: enhancement

#109 [Fix] home화면 비디오 조회수 및 좋아요 표시숫자 수정, 간격조절
  Media/Presentation/Home/HomeViewController.swift
  Media/Presentation/Home/VideoCell/VideoCell.xib
  Media/Presentation/Home/VideoCell/VideoCellViewModel.swift
Labels: enhancement

#110 feat: `Playable` 프로토콜에 설정된 비디오 품질에 따라 비디오를 달리 재생하도록 도와주는 메서드 구현
  Media/Core/Protocols/VideoPlayable.swift
  Media/Model/Videos/VideoQuality.swift
  Media/Model/Videos/VideoVariants.swift
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/VideoListViewController.swift
  Media/Presentation/Home/VideoCell/VideoCellUsing.swift
Labels: enhancement

#112 fix: 네트워크 불량 환경에서 비디오 재생 시도 시, 네트워크 불량 알림이 제대로 뜨지 않는 문제 수정
  Media/Core/Protocols/Alertable.swift
  Media/Core/Protocols/VideoPlayable.swift
  Media/Infrastructure/VideoPlayer/Cacher/VideoCacher.swift
  Media/Infrastructure/VideoPlayer/Cacher/VideoCacherLogger.swift
  Media/Infrastructure/VideoPlayer/VideoPlayerError.swift
  Media/Infrastructure/VideoPlayer/VideoPlayerService.swift
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/VideoListViewController.swift
Labels: QA, 북마크, 북마크(상세목록)

#156 fix: 모달 뷰 상단 패딩 문제 해결을 위해 NavigationController로 래핑
  Media/Presentation/Settings/SettingsTableViewController.swift
Labels: QA, 설정(상세화면)

#159 [Fix] 홈에서 재생목록 비디오 중복처리 완료, 태그/시간 라벨 다크모드대응, 홈화면 카테고리 테두리변경, 카테고리갱신
  Media/Presentation/Home/CategoryCell/CategoryCell.swift
  Media/Presentation/Home/HomeViewController.swift
  Media/Presentation/Home/VideoCell/VideoCell.swift
  Media/Presentation/Home/VideoCell/VideoCell.xib
Labels: QA

#162 fix: `TagsSelectedViewController`에서 `Confirm` 버튼 클릭 시, 전체 데이터가 삭제되는 코드 삭제, 북마크 화면 또는 홈 화면 진입 시 크래시나는 오류 수정
  Media/Application/AppDelegate.swift
  Media/Infrastructure/Storage/CoreData/CoreDataService+Defaults.swift
  Media/Infrastructure/Storage/CoreData/CoreDataService+Dummy.swift
  Media/Infrastructure/Storage/UserDefaults/UserDefaultsKeys.swift
  Media/Infrastructure/VideoPlayer/PIPVideoPlayerViewController.swift
  Media/Infrastructure/VideoPlayer/VideoPlayerService.swift
  Media/Presentation/SelectedCategory/SelectedTagsViewController.swift
Labels: QA, 북마크

#160 fix: 검색 테이블 뷰 하단에 그림자 추가, 검색 끝나면 스크롤 할 때 키보드 &검색 테이블 뷰 사라지도록 변경 등
  Media/Model/API/Category.swift
  Media/Presentation/Search/SearchFilterViewController.swift
  Media/Presentation/Search/SearchResultViewController.swift
  Media/Presentation/Search/SearchViewController.swift
  Media/Presentation/Search/TVCell/SearchTableViewCell.xib
Labels: QA, 검색(최근검색목록)

#164 fix: 플레이리스트 폴더 컨텍스트 메뉴 선택시 셀 전체 강조가 아니라 플레이리스트 폴더 이미지만 강조
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/View/Cells/SmallVideoCell.swift
  Media/Presentation/Bookmark/View/Cells/SmallVideoCell.xib
Labels: QA, 북마크

#168 [Fix] 홈화면에서 비디오 재생이 안되던 현상 수정
  Media/Presentation/Home/HomeViewController.swift
Labels: bug, QA, 홈

#186 Fix: 홈에서 팝오버를 띄운 채로 화면 회전하면 팝오버 사라지도록 변경(iPad), 네트워크 연결 끊겼을 때 place holder 이미지 추가
  Media/Presentation/Search/SearchResultViewController.storyboard
  Media/Presentation/Search/SearchResultViewController.swift
  Media/Resources/Assets.xcassets/ImageSet/no_internet.imageset/ChatGPT Image 2025년 6월 16일 오후 05_57_45.png
  Media/Resources/Assets.xcassets/ImageSet/no_internet.imageset/ChatGPT Image 2025년 6월 16일 오후 06_03_22.png
  Media/Resources/Assets.xcassets/ImageSet/no_internet.imageset/Contents.json
Labels: QA, 홈, 검색

#187 [Fix] popover 화면전환시 제거, 비디오재생이후 리로드 삭제
  Media/Core/Protocols/VideoPlayable.swift
  Media/Presentation/Home/HomeViewController.swift
Labels: QA, 홈

#189 fix: 비디오 퀄리티 변경 시 섹션 사이즈 변경되는 버그
  Media/Presentation/Settings/SettingsTableViewController.swift
Labels: bug, QA, 설정

#194 [Feat] Home 화면에서 네트워크 연결안될경우 이미지 추가
  Media/Presentation/Home/HomeViewController.storyboard
  Media/Presentation/Home/HomeViewController.swift
Labels: QA, 홈

#218 fix: 비디오 퀄리티 데이터 Userdefault에 저장이 제대로 안되는 버그
  Media/Application/SceneDelegate.swift
  Media/Infrastructure/Storage/UserDefaults/UserDefaultsKeys.swift
  Media/Presentation/Settings/SettingsTableViewController.swift
Labels: QA, 설정

#220 fix: 북마크 화면에서 재생 목록이 제대로 삭제되지 않는 문제 수정, 사용자 프로필 이미지가 없는 비디오를 삭제할 때 크래시가 나는 문제 수정, 재생 기록에 의도치 않게 비디오가 추가되는 문제 수정 등
  Media/Infrastructure/VideoPlayer/VideoPlayerService.swift
  Media/Model/CoreData/Media.xcdatamodeld/Media.xcdatamodel/contents
  Media/Presentation/Bookmark/BookmarkViewController.swift
  Media/Presentation/Bookmark/VideoListViewController.swift
  Media/Presentation/Bookmark/View/Cells/MediumVideoCell.swift
  Media/Presentation/Bookmark/View/Cells/SmallVideoCell.swift
  Media/Presentation/Home/HomeViewController.swift
  Media/Resources/Assets.xcassets/ImageSet/no_playlist.imageset/Contents.json
  Media/Resources/Assets.xcassets/ImageSet/no_playlist.imageset/no_playlist_dark.png
  Media/Resources/Assets.xcassets/ImageSet/no_playlist.imageset/no_playlist_light.png
Labels: QA, 북마크, 공통 코드

#228 [Fix] 에셋사진이름 수정
  Media/Resources/Assets.xcassets/ImageSet/no_internet.imageset/Contents.json
  Media/Resources/Assets.xcassets/ImageSet/no_internet.imageset/noInternetdark@2x.png
  Media/Resources/Assets.xcassets/ImageSet/no_internet.imageset/noInternetlight@2x.png
  Media/Resources/Assets.xcassets/ImageSet/no_profile.imageset/Contents.json
  Media/Resources/Assets.xcassets/ImageSet/no_profile.imageset/noprofile@2x.png
Labels: bug, QA, 홈, 검색

#225 fix: 탭바 순서 변경하기(Interest-Library)
  Media/Application/SceneDelegate.swift
  Media/Presentation/Home/HomeViewController.swift
Labels: QA, 공통 코드

#232 fix: 이미지 리소스가 제대로 할당되지 않는 문제, fix: 검색 쿼리를 클릭하면 하이라이트 강조, 검색 결과 뷰에서 playTime이 넘어가지 않는 오류 수정
  Media.xcodeproj/project.pbxproj
  Media/Infrastructure/Storage/VideoDataService/VideoDataService.swift
  Media/Presentation/Search/CVCell/FilterCategoryCollectionViewCell.swift
  Media/Presentation/Search/CVCell/FilterOrderCollectionViewCell.swift
  Media/Presentation/Search/CVCell/FilterVideoDurationCollectionViewCell.swift
  Media/Presentation/Search/SearchFilterViewController.storyboard
  Media/Presentation/Search/SearchResultViewController.swift
  Media/Presentation/Search/TVCell/SearchTableViewCell.swift
Labels: QA, 검색(최근검색목록), 검색

#236 fix: 검색 필터화면에서 시트 뒷배경 어둡게 변경
  Media/Presentation/Search/SearchFilterViewController.swift
  Media/Presentation/Search/SearchResultViewController.swift
  Media/Presentation/Search/SearchViewController.swift
Labels: QA, 검색(최근검색목록), 검색

#239 fix: 아이패드 환경에서 북마크의 재생 기록(Playback) 셀의 너비 수정
  Media/Presentation/Bookmark/Section/BookmarkSection.swift
Labels: 북마크

#241 fix: 취향 선택 카테고리 셀의 shadow opacity 제거
  Media/Presentation/SelectedCategory/SelectedTagsViewController.swift
Labels: bug, QA, 취향선택

#246 fix: 누락된 PiP 모드 다시 추가
  Media/Resources/Info.plist
Labels: bug, QA, 공통 코드

#251 Hotfix: filterView 하단의 버튼 stackView bottom constraint 조정
  Media/Presentation/Search/SearchFilterViewController.storyboard
  Media/Presentation/Search/SearchFilterViewController.swift
  Media/Presentation/Settings/SettingsViewController.storyboard
Labels: bug, 검색
